article_module/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.ArticleListView.as_view(), name='article_page'),
    path('cat/<str:category>/', views.ArticleListView.as_view(), name='article_by_category'),
    path('<pk>/', views.ArticleDetailView.as_view(), name='article_detail_page'),
    path('add-article-comment', views.add_article_comment, name='add_article_comment')
]

eshop_project/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('home_module.urls')),
    path('', include('user_module.urls')),
    path('contact-us/', include('contact_module.urls')),
    path('article/', include('article_module.urls')),
    path('products/', include('product_module.urls')),
    path('user/', include('user_panel.urls')),
    path('admin/', admin.site.urls)

]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

user_panel/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.UserPanelView.as_view(), name="user_panel_page"),
    path('change-password/', views.ChangePasswordView.as_view(), name="change_password"),
    path('edit-profile/', views.EditUserPanelView.as_view(), name="edit_user_profile")

]

article_module/models.py
from django.db import models
from user_module.models import User


class ArticleCategory(models.Model):
    parent = models.ForeignKey('ArticleCategory', null=True, blank=True,
                               on_delete=models.CASCADE,
                               verbose_name='Parent category')
    title = models.CharField(max_length=300, verbose_name='Title of category')
    url_title = models.CharField(max_length=400, unique=True, verbose_name='Title of Url')
    is_active = models.BooleanField(default=True, verbose_name='Enable/Disable')

    class Meta:
        verbose_name = 'Article Category'
        verbose_name_plural = 'Article Categories'

    def __str__(self):
        return self.title


class Article(models.Model):
    title = models.CharField(max_length=200, verbose_name='Title of Article')
    slug = models.SlugField(max_length=400, db_index=True, allow_unicode=True, verbose_name='Title of Url')
    image = models.ImageField(upload_to='images/articles/', verbose_name='Picture')
    short_desc = models.TextField(verbose_name='Short Description')
    text = models.TextField(verbose_name='Text of article')
    is_active = models.BooleanField(default=True, verbose_name='Enable/Disable')
    selected_categories = models.ManyToManyField(ArticleCategory, verbose_name='Categories')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Author', null=True, editable=False)
    create_date = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='Registration Date')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'


class ArticleComment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name='Article')
    parent = models.ForeignKey('ArticleComment', null=True, blank=True, on_delete=models.CASCADE, verbose_name='Parent')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='User')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='Create Date')
    text = models.TextField(verbose_name='Text')

    class Meta:
        verbose_name = 'Article Comment'
        verbose_name_plural = 'Article Comments'

    def __str__(self):
        return str(self.user)

article_module/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from article_module.models import Article, ArticleCategory, ArticleComment


class ArticleListView(ListView):
    model = Article
    template_name = 'article_module/article_page.html'
    paginate_by = 5

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context

    def get_queryset(self):
        query = super(ArticleListView, self).get_queryset()
        category_name = self.kwargs.get('category')
        query = query.filter(is_active=True)
        if category_name is not None:
            query = query.filter(selected_categories__url_title__iexact=category_name)
        return query


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'article_module/article_detail_page.html'

    def get_queryset(self):
        query = super(ArticleDetailView, self).get_queryset()
        query = query.filter(is_active=True)
        return query

    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView, self).get_context_data(**kwargs)
        article = self.object
        context['comments'] = ArticleComment.objects.filter(article_id=article.id, parent=None).order_by(
            '-create_date').prefetch_related('articlecomment_set__user')
        context['comments_count'] = ArticleComment.objects.filter(article_id=article.id).count()
        return context


def article_categories_component(request: HttpRequest):
    article_main_categories = ArticleCategory.objects.filter(is_active=True, parent_id=None).prefetch_related('articlecategory_set')
    context = {
        'main_categories': article_main_categories
    }
    return render(request, 'article_module/components/article_categories_component.html', context)


def add_article_comment(request: HttpRequest):
    if request.user.is_authenticated:
        comment = request.GET.get('article_comment')
        article_id = request.GET.get('article_id')
        parent_id = request.GET.get('parent_id')

        new_comment = ArticleComment(article_id=article_id, text=comment, parent_id=parent_id, user_id=request.user.id)
        new_comment.save()
        context = {
            'comments': ArticleComment.objects.filter(article_id=article_id, parent=None).order_by(
            '-create_date').prefetch_related('articlecomment_set__user'),
            'comments_count': ArticleComment.objects.filter(article_id=article_id).count()
        }
        return render(request, 'article_module/includes/article_comment_partial.html', context)
    return HttpResponse('response')

article_module/templates/article_module/includes/article_comment_partial.html
{% load thumbnail %}
{% load poll_extras %}

<h2>نظر ها ({{ comments_count }})</h2>
<ul class="media-list">
    {% for comment in comments %}
        <li class="media" id="single_comment_area{{ comment.id }}">
            <a class="pull-right" href="#">
                {% if comment.user.avator %}
                    {% thumbnail comment.user.avator '121x86' crop='center' as im %}
                        <img class="media-object" src="{{ im.url }}" alt="">
                    {% endthumbnail %}
                {% else %}
                    <img class="media-object" src="/static/images/blog/Customer.jpg" alt="">
                {% endif %}
            </a>
            <div class="media-body">
                <ul class="sinlge-post-meta">
                    <li><i class="fa fa-user"></i>{{ comment.user }}</li>
                    <li><i class="fa fa-clock-o"></i>{{ comment.create_date | show_time }}</li>
                    <li>
                        <i class="fa fa-calendar"></i>{{ comment.create_date | show_date2jalali }}
                    </li>
                </ul>
                <p>{{ comment.text }}</p>
                <a class="btn btn-primary" onclick="fillParentId({{ comment.id }})"><i class="fa fa-reply"></i>پاسـخ</a>
            </div>
        </li>

        {% for sub_comment in comment.articlecomment_set.all %}
            <li class="media second-media" id="single_comment_area{{ comment.id }}">
                <a class="pull-right" href="#">
                    {% if sub_comment.user.avator %}
                        {% thumbnail sub_comment.user.avator '121x86' crop='center' as im %}
                            <img class="media-object" src="{{ im.url }}" alt="">
                        {% endthumbnail %}
                    {% else %}
                        <img class="media-object" src="/static/images/blog/Customer.jpg" alt="">
                    {% endif %}
                </a>
                <div class="media-body">
                    <ul class="sinlge-post-meta">
                        <li><i class="fa fa-user"></i>{{ sub_comment.user }}</li>
                        <li>
                            <i class="fa fa-clock-o"></i>{{ sub_comment.create_date | show_time }}
                        </li>
                        <li>
                            <i class="fa fa-calendar"></i>{{ sub_comment.create_date | show_date2jalali }}
                        </li>
                    </ul>
                    <p>{{ sub_comment.text }}</p>
                    {% comment %} <a class="btn btn-primary" href=""><i class="fa fa-reply"></i>پاسـخ</a>{% endcomment %}
                </div>
            </li>

        {% endfor %}
    {% endfor %}
</ul>